# Wazuh App Copyright (C) 2018 Wazuh Inc. (License GPLv2)
version: '2'

services:
  base:
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./v/tools:/srv/tools
    logging:
      options:
        max-size: "2048m"
        max-file: "20"
  wazuh:
    image: wazuh/wazuh:3.8.0_6.5.4
    hostname: wazuh-manager
    restart: always
    extends: base
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
      - "1516:1516"
    networks:
      - docker_elk
    volumes:
      - ./v/wazuh/ossec/data:/var/ossec/data:Z
      # - ./v/wazuh/postfix:/etc/postfix:Z
      # - ./v/wazuh/filebeat:/etc/filebeat
      # - ./v/wazuh/config/ossec.conf:/wazuh-config-mount/etc/ossec.conf
    command: ["echo 'hello world'"]
    depends_on:
      - logstash
  logstash:
    image: wazuh/wazuh-logstash:3.8.0_6.5.4
    hostname: logstash
    restart: always
    extends: base
    volumes:
      - ./v/logstash/data:/etc/logstash/conf.d:Z
    links:
      - elasticsearch:elasticsearch
    ports:
      - "5000:5000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      - LS_HEAP_SIZE=2048m
  elasticsearch:
    image: elasticsearch:6.5.4
    hostname: elasticsearch
    restart: always
    extends: base
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=node-1
      - cluster.name=wazuh
      - network.host=0.0.0.0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./v/elasticsearch/data:/usr/share/elasticsearch/data:Z
    networks:
        - docker_elk
  kibana:
    image: wazuh/wazuh-kibana:3.8.0_6.5.4
    hostname: kibana
    restart: always
    extends: base
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh
  # nginx:
  #   image: wazuh/wazuh-nginx:3.8.0_6.5.4
  #   hostname: nginx
  #   restart: always
  #   extends: base
  #   environment:
  #     - NGINX_PORT=443
  #   ports:
  #     - "80:80"
  #   # volumes:
  #     # - ./v/nginx/config/conf.d:/etc/nginx/conf.d:Z
  #   networks:
  #     - docker_elk
  #   depends_on:
  #     - kibana
  #   links:
  #     - kibana:kibana

networks:
  docker_elk:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
